module.exports = {
  CHART_FAIL: "Lấy dữ liệu biểu đồ thất bại!",
  GET_LIST_SUCCESS: "Lấy danh sách thành công!",
  GET_LIST_EMPTY: "Danh sách trống!",
  GET_LIST_FAIL: "Lấy danh sách thất bại!",
  //Email
  SEND_EMAIL_PASS: "Vào mail để lấy mật khẩu mới!",
  SEND_EMAIL_UNLOCK: "Đã gửi mail cấp quyền!",

  //Đổi mật khẩu
  PASS_OLD_WRONG: "Mật khẩu cũ sai!",
  PASS_CHANGE_SUCCESS: "Đổi mật khẩu thành công!",
  PASS_CHANGE_FAIL: "Đổi mật khẩu thất bại!",
  PASS_OLD_EMPTY: "Chưa nhập mật khẩu cũ!",
  PASS_NEW_EMPTY: "Chưa nhập mật khẩu mới!",
  PASS_REPASS_WRONG: "Nhập lại mật khẩu không trùng khớp!",

  //Login
  LOGIN_EMAIL_WRONG: "Tài khoản không tồn tại!",
  LOGIN_PASS_WRONG: "Sai mật khẩu!",
  LOGIN_EMAIL_LOCK: "Tài khoản này đã bị khóa!",
  LOGIN_EMAIL_ERROR: "Tài khoản này chưa được cấp quyền!",
  LOGIN_SUCCESS: "Đăng nhập thành công!",
  LOGIN_FAIL: "Đăng nhập thất bại",

  // Thông tin
  INF_NAME_EMPTY_ERROR: "Họ tên không được để trống!",
  INF_EMAIL_EMPTY_ERROR: "Email không được để trống!",
  INF_PHONE_EMPTY_ERROR: "Số điện thoại không được để trống!",
  INF_ID_EMPTY_ERROR: "CCCD không được để trống!",
  INF_BIRTHDAY_EMPTY_ERROR: "Ngày sinh không được để trống!",
  INF_ADDRESS_EMPTY_ERROR: "Địa chỉ không được để trống!",

  INF_EMAIL_FORMAT_ERROR: "Email không hợp lệ!",
  INF_PHONE_FORMAT_ERROR: "Số điện thoại không hợp lệ!",
  INF_ID_FORMAT_ERROR: "CCCD phải là dãy số có độ dài là 12!",
  INF_BIRTHDAY_FUTURE_ERROR: "Ngày sinh không hợp lệ!",

  INF_EXISTED_EMAIL_ERROR: "Email này đã được tài khoản khác đăng ký!",

  INF_LONG_NAME_ERROR: "Họ tên không được vượt quá 50 ký tự!",
  INF_LONG_EMAIL_ERROR: "Email không được vượt quá 50 ký tự!",
  INF_LONG_ADDRESS_ERROR: "Địa chỉ không được vượt quá 50 ký tự!",

  INF_PASSWORD_EMPTY_ERROR: "Mật khẩu không được để trống!",
  INF_PASSWORD_FORMAT_ERROR: "Mật khẩu phải có độ dài lớn hơn 8 và nhỏ hơn 12!",
  INF_REPASS_EMPTY_ERROR: "Bạn chưa nhập lại mật khẩu!",
  INF_REPASS_ERROR: "Nhập lại mật khẩu không khớp!",

  INF_SUCCESS: "Đăng ký thành công. Tài khoản đang chờ được phê duyệt!",
  INF_FAIL: "Đăng ký thất bại!",
  ERROR: "Đã có lỗi xảy ra!",

  INF_UPDATE_SUCCESS: "Cập nhật thông tin thành công!",
  INF_UPDATE_FAIL: "Cập nhật thông tin thất bại!",

  //Lịch Chiếu
  SHOWCASE_ROOM_EMPTY_ERROR: "Bạn chưa chọn phòng!",
  SHOWCASE_MOVIE_EMPTY_ERROR: "Bạn chưa chọn phim!",
  SHOWCASE_DATETIME_EMPTY_ERROR: "Ngày chiếu - Giờ chiếu không được để trống!",
  SHOWCASE_DATETIME_LATE_ERROR: "Thời gian chiếu không hợp lệ!",
  SHOWCASE_PRICE_EMPTY_ERROR: "Bạn chưa chọn giá vé!",
  SHOWCASE_DATEPAST_ERROR: "Ngày chiếu - Giờ chiếu không hợp lệ!",
  SHOWCASE_ADD_SUCCESS: "Thêm lịch chiếu thành công!",
  SHOWCASE_ADD_FAIL: "Thêm lịch chiếu thất bại!",
  SHOWCASE_UPDATE_SUCCESS: "Cập nhật lịch chiếu thành công!",
  SHOWCASE_UPDATE_FAIL: "Cập nhật lịch chiếu thất bại!",
  SHOWCASE_CANCEL_SUCCESS: "Hủy lịch chiếu thành công!",
  SHOWCASE_CANCEL_FAIL: "Hủy lịch chiếu thất bại!",
  SHOWCASE_GETLIST_SUCCESS: "Lấy danh sách lịch chiếu thành công!",
  SHOWCASE_GETLIST_FAIL: "Lấy danh sách lịch chiếu thất bại!",
  SHOWCASE_UPDATE_STATUS_FAIL: "Cập nhật trạng thái lịch chiếu thất bại!",

  //Nhân viên
  STAFF_UPDATE_SUCCESS: "Cập nhật thông tin nhân viên thành công!",
  STAFF_UPDATE_FAIL: "Cập nhật thông tin nhân viên thất bại!",
  STAFF_NOT_EXISTS: "Nhân viên không tồn tại!",

  //Phòng
  ROOM_NAME_EMPTY_ERROR: "Tên phòng không được để trống!",
  ROOM_CAPACITY_EMPTY_ERROR: "Số ghế tối đa không được để trống!",
  ROOM_ROW_EMPTY_ERROR: "Số hàng không được để trống!",
  ROOM_COL_EMPTY_ERROR: "Số cột không được để trống!",
  ROOM_IMG_EMPTY_ERROR: "Bạn chưa chọn ảnh!",
  ROOM_SAME_NAME_ERROR: "Tên phòng đã tồn tại trong chi nhánh này!",
  ROOM_ROW_CAPACITY_ERROR: "Số hàng phải nhỏ hơn hoặc bằng ",
  ROOM_COL_ROW_ERROR: "Số cột phải bằng ",
  ROOM_COL_ROW_ERROR2: "Số cột phải nhỏ hơn hoặc bằng ",
  ROOM_COL_NEGATIVE_ERROR: "Số cột phải lớn hơn hoặc bằng 0!",
  ROOM_ROW_NEGATIVE_ERROR: "Số hàng phải lớn hơn hoặc bằng 0!",
  ROOM_CAPACITY_NEGATIVE_ERROR: "Số ghế tối đa phải lớn hơn hoặc bằng 0!",
  ROOM_CAPACITY_LIMIT_ERROR: "Số ghế tối đa phải nhỏ hơn hoặc bằng 676!",
  ROOM_SUCCESSS: "Thêm phòng chiếu thành công!",
  ROOM_FAIL: "Thêm phòng chiếu thất bại!",
  ROOM_UPDATE_SUCCESS: "Cập nhật phòng chiếu thành công!",
  ROOM_UPDATE_FAIL: "Cập nhật phòng chiếu thất bại!",
  ROOM_DELETE_ERROR: "Không được xóa!Phòng này có trong lịch chiếu",
  ROOM_DELETE_SUCCESS: "Xóa phòng thành công!",
  ROOM_DELETE_FAIL: "Xóa phòng thất bại!",
  ROOM_GET_HIS: "Lấy danh sách lịch sử sử dụng thành công!",
  ROOM_EMPTY: "Không có phòng trống!",

  //Chi nhánh
  BRANCH_NAME_EMPTY: "Tên chi nhánh không được để trống!",
  BRANCH_NAME_EXISTS: "Tên chi nhánh đã tồn tại!",
  BRANCH_ADD_SUCCESS: "Thêm chi nhánh thành công!",
  BRANCH_ADD_FAIL: "Thêm chi nhánh thất bại!",
  BRANCH_NAME_LONG: "Tên chi nhánh không vượt quá 50 ký tự!",
  BRANCH_UPDATE_SUCCESS: "Cập nhật chi nhánh thành công!",
  BRANCH_UPDATE_FAIL: "Cập nhật chi nhánh thất bại!",
  BRANCH_DELETE_FAIL: "Không được xóa chi nhánh này!",
  BRANCH_DELETE_SUCCESS: "Xóa chi nhánh thành công!",

  //Cơ sở vật chất
  FAC_NAME_EMPTY: "Tên cơ sở vật chất không được để trống!",
  FAC_ADD_SUCCESS: "Thêm cơ sở vật chất thành công!",
  FAC_ADD_FAIL: "Thêm cơ sở vật chất thất bại!",
  FAC_EXISTS: "Cơ sở vật chất này đã có trong phòng!",
  FAC_NAME_LONG: "Tên CSVC không vượt quá 30 ký tự!",
  FAC_UPDATE_SUCCESS: "Cập nhật cơ sở vật chất thành công!",
  FAC_UPDATE_FAIL: "Cập nhật cơ sở vật chất thất bại!",
  FAC_UPDATE_STATUS_SUCCESS: "Cập nhật trạng thái cơ sở vật chất thành công!",
  FAC_UPDATE_STATUS_FAIL: "Cập nhật trạng thái cơ sở vật chất thất bại!",
  FAC_DELETE_SUCCESS: "Xóa cơ sở vật chất thành công!",
  FAC_DELETET_FAIL: "Xóa cơ sở vật chất thất bại!",

  //Phim
  MOVIE_NAME_EMPTY: "Tên phim không để trống!",
  MOVIE_PROCOUNTRY_EMPTY: "Nước sản xuất không để trống!",
  MOVIE_PREDATE_EMPTY: "Ngày khởi chiếu không để trống!",
  MOVIE_PREDATE_ERROR: "Ngày khởi chiếu không hợp lệ!",
  MOVIE_DURATION_EMPTY: "Thời lượng không để trống!",
  MOVIE_DIRECTOR_EMPTY: "Đạo diễn không để trống!",
  MOVIE_ACTOR_EMPTY: "Diễn viên không để trống!",
  MOVIE_GENRE_EMPTY: "Thể loại không để trống!",
  MOVIE_DESCRIBE_EMPTY: "Mô tả không để trống!",
  MOVIE_ADD_SUCCESS: "Thêm phim thành công!",
  MOVIE_ADD_FAIL: "Thêm phim thất bại!",
  MOVIE_UPDATE_SUCCESS: "Cập nhật phim thành công!",
  MOVIE_UPDATE_FAIL: "Cập nhật phim thất bại!",
  MOVIE_DELETE_ERROR: "Không được xóa phim đã có lịch chiếu!",
  MOVIE_DELETE_SUCCESS: "Xóa phim thành công!",
  MOVIE_DELETE_FAIL: "Xóa phim thất bại!",

  //Giá vé
  TICKET_NAME_EMPTY: "Tên giá vé không để trống!",
  TICKET_PRICE_EMPTY: "Giá vé không để trống!",
  TICKET_PRICE_FORMAT: "Giá vé là số!",
  TICKET_NAME_LONG: "Tên giá vé không quá 20 ký tự!",
  TICKET_ADD_SUCCESS: "Thêm giá vé thành công!",
  TICKET_ADD_FAIL: "Thêm giá vé thất bại!",
  TICKET_UPDATE_SUCCESS: "Cập nhật giá vé thành công!",
  TICKET_UPDATE_FAIL: "Cập nhật giá vé thất bại!",
  TICKET_DELETE_ERROR: "Không được xóa giá vé đã áp dụng trong lịch chiếu!",
  TICKET_DELETE_SUCCESS: "Xóa giá vé thành công!",
  TICKET_DELETE_FAIL: "Xóa giá vé thất bại!",
};
